 /* 
 * File:   enum_TCPServer.h
 * Author: AnkurChauhan
 *
 * Created on April 26, 2017, 7:59 PM
 */

#ifndef ENUM_TCPSERVER_H

enum Req_MsgCode
{
  ENUM_LOGON_MESSAGE = 1,
  ENUM_LOGIN_RESPONSE = 2,
  ENUM_TOKEN_DATA = 3,
  ENUM_LIMIT_UPLOAD_TOOL_LEVEL = 4,
  ENUM_LIMIT_UPLOAD_TOOL_LEVEL_TO_ALL_CONNECTED = 5,
  ENUM_LIMIT_UPLOAD_TOKEN_LEVEL = 6,
  ENUM_LIMIT_UPLOAD_TOKEN_LEVEL_TO_ALL_CONNECTED = 7,
  ENUM_TEMP_PORTFOLIO = 8,
  ENUM_F2F_PORTFOLIO = 9,
  ENUM_KILL_SWITCH_ACTIVATION = 10,
  ENUM_KILL_RESPONSE_TO_ALL = 11,
  ENUM_LIMIT_UPLOAD_TOKEN_LEVEL_FOR_BAN_UNBAN = 12,
  ENUM_LIMIT_UPLOAD_TOKEN_LEVEL_FOR_BAN_UNBAN_TO_ALL = 13,
  ENUM_START_STOP_REQ = 14,
  ENUM_START_STOP_RESP =15,
  ENUM_LIMIT_UPDATE_TOKEN_LEVEL_TO_ALL = 16,
  ENUM_TRADE_POSITION_PORTFOLIO_UPDATE_ALL_USERS = 17,
  ENUM_UNSOLICITED_MESSAGE_TO_DEALER = 18,
};

#define	ENUM_TCPSERVER_H



#endif	/* ENUM_TCPSERVER_H */

